Update inc-file-sn to Handle Suffix

diff --git a/inc-file-sn b/inc-file-sn
--- a/inc-file-sn
+++ b/inc-file-sn
@@ -8,21 +8,37 @@ if [[ -z "$inc" ]]; then
 fi
 shift
 
-for f in "$@"; do
-    fname="${f%.*}"
-    ext="${f:${#fname}}"
-    prefix="${fname%%[0-9][0-9]*}"
-    sn="${fname:${#prefix}}"
+function rename {
+    if [[ $1 == "-n" ]]; then
+        is_dry=1
+        shift 1
+    fi
 
-    new_sn=$((10#$sn + 10#$inc))            # enfore decimal even leading zero
-    new_sn=$(printf "%0*d" ${#sn} $new_sn)  # padding leading zero if shortened
+    for f in $(printf '%s\n' "$@" | sort -r) ; do
+        fname="${f%.*}"
+        ext="${f:${#fname}}"
+        prefix="${fname%%[0-9]*}"
+        suffix="${fname##*[0-9]}"
+        sn="${fname:${#prefix}:${#fname}-${#prefix}-${#suffix}}"
 
-    new_f="$prefix$new_sn$ext"
+        new_sn=$((10#$sn + 10#$inc))            # enfore decimal even leading zero
+        new_sn=$(printf "%0*d" ${#sn} $new_sn)  # padding leading zero if shortened
 
-    echo "[+] mv $f $new_f"
-    mv "$f" "$new_f"
-done
+        new_f="$prefix$new_sn$suffix$ext"
 
+        if [[ -e "$new_f" ]]; then
+            >&2 echo "error: target file exists: mv $f $new_f"
+            exit 9
+        fi
+        if [[ -z $is_dry ]]; then
+            echo "[+] mv $f $new_f"
+            mv "$f" "$new_f"
+        fi
+    done
+}
+
+#rename -n "$@" #not work
+rename "$@"
 
 
 
